In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Read the books dataset and explore it


In [ ]:
df_user=pd.read_csv('BX-Users.csv',encoding='latin-1')

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
df_user.head()

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [ ]:
#Clean up NaN values

In [ ]:
df_user.isnull().sum()

user_id          0
Location         1
Age         110763
dtype: int64

In [ ]:
df_user['Age'].fillna(df_user['Age'].mean(),inplace=True)

In [ ]:
df_user['Location'].fillna('NA',inplace=True)

In [ ]:
df_user.isnull().sum()

user_id     0
Location    0
Age         0
dtype: int64

In [ ]:
df_books=pd.read_csv('BX-Books.csv',encoding='latin-1')

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
df_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [ ]:
df_books.isnull().sum()

isbn                   0
book_title             0
book_author            1
year_of_publication    0
publisher              2
dtype: int64

In [ ]:
df_books.dropna(inplace=True)

In [ ]:
df=pd.read_csv('BX-Book-Ratings.csv',encoding='latin-1',nrows=10000)

In [ ]:
df.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [ ]:
df.describe()

user_id        rating
count   10000.000000  10000.000000
mean   265844.379600      1.974700
std     56937.189618      3.424884
min         2.000000      0.000000
25%    277478.000000      0.000000
50%    278418.000000      0.000000
75%    278418.000000      4.000000
max    278854.000000     10.000000

In [ ]:
df.isnull().sum()

user_id    0
isbn       0
rating     0
dtype: int64

In [ ]:
df=pd.merge(df,df_books, on='isbn')

In [ ]:
df

user_id        isbn  rating                book_title  \
0      276725  034545104X       0      Flesh Tones: A Novel   
1      276726   155061224       5          Rites of Passage   
2      276727   446520802       0              The Notebook   
3      278418   446520802       0              The Notebook   
4      276729  052165615X       3            Help!: Level 1   
...       ...         ...     ...                       ...   
8696      243   385720106       7        A Map of the World   
8697      243   425092917       0    The Accidental Tourist   
8698      243   425098834       0     If Morning Ever Comes   
8699      243   425163407       9        Unnatural Exposure   
8700      243   425164403       0  Only Love (Magical Love)   

                    book_author year_of_publication  \
0                    M. J. Rose                2002   
1                    Judith Rae                2001   
2               Nicholas Sparks                1996   
3               Nicholas Sparks                1996   
4                 Philip Prowse                1999   
...                         ...                 ...   
8696              Jane Hamilton                1999   
8697                 Anne Tyler                1994   
8698                 Anne Tyler                1983   
8699  Patricia Daniels Cornwell                1998   
8700                Erich Segal                1998   

                       publisher  
0               Ballantine Books  
1                         Heinle  
2                   Warner Books  
3                   Warner Books  
4     Cambridge University Press  
...                          ...  
8696      Anchor Books/Doubleday  
8697    Berkley Publishing Group  
8698    Berkley Publishing Group  
8699    Berkley Publishing Group  
8700    Berkley Publishing Group  

[8701 rows x 7 columns]

In [ ]:
# Take a quick look at the number of unique users and books

In [ ]:
n_users=df.user_id.nunique()
n_books=df.isbn.nunique()
print('Num of Users: ' + str(n_users))
print('Num of Books: '+str(n_books))

Num of Users: 828
Num of Books: 8051


In [ ]:
#Convert ISBN variables to numeric numbers in the correct order

In [ ]:
isbn_list=df.isbn.unique()
print('Lenth of isbn List:',len(isbn_list))
def get_isbn_numeric_id(isbn):
  print('isbn is:',isbn)
  itemindex=np.where(isbn_list==isbn)
  return itemindex[0][0]

Lenth of isbn List: 8051


In [ ]:
df['isbn_id']=df['isbn'].apply(get_isbn_numeric_id)

Streaming output truncated to the last 5000 lines.
isbn is: 380701006
isbn is: 380705257
isbn is: 380772469
isbn is: 380818760
isbn is: 038082082X
isbn is: 039308647X
isbn is: 394801962
isbn is: 394831993
isbn is: 425044602
isbn is: 042510107X
isbn is: 425115291
isbn is: 425120430
isbn is: 425142078
isbn is: 425144917
isbn is: 425147738
isbn is: 425174638
isbn is: 425180964
isbn is: 425182142
isbn is: 425182142
isbn is: 042518904X
isbn is: 440122090
isbn is: 440200946
isbn is: 440209285
isbn is: 440223571
isbn is: 440223571
isbn is: 440223571
isbn is: 440237300
isbn is: 440426766
isbn is: 440457165
isbn is: 440457610
isbn is: 441659489
isbn is: 441783317
isbn is: 446327638
isbn is: 446354732
isbn is: 446611867
isbn is: 446611867
isbn is: 449000613
isbn is: 449002357
isbn is: 449208672
isbn is: 449704408
isbn is: 451180348
isbn is: 505524678
isbn is: 515084166
isbn is: 515106402
isbn is: 515110973
isbn is: 515124621
isbn is: 515130648
isbn is: 515134368
isbn is: 517007215
isbn is: 52342

In [ ]:
df.head(20)

user_id        isbn  rating  \
0    276725  034545104X       0   
1    276726   155061224       5   
2    276727   446520802       0   
3    278418   446520802       0   
4    276729  052165615X       3   
5    276729   521795028       6   
6    276733  2080674722       0   
7    276744  038550120X       7   
8    278418  038550120X       0   
9    276746   425115801       0   
10   277427   425115801       0   
11   276746   449006522       0   
12   278026   449006522       8   
13   276746   553561618       0   
14   276746  055356451X       0   
15   278418  055356451X       0   
16   276746   786013990       0   
17   276746   786014512       0   
18   276747    60517794       9   
19   278843    60517794       7   

                                           book_title         book_author  \
0                                Flesh Tones: A Novel          M. J. Rose   
1                                    Rites of Passage          Judith Rae   
2                                        The Notebook     Nicholas Sparks   
3                                        The Notebook     Nicholas Sparks   
4                                      Help!: Level 1       Philip Prowse   
5   The Amsterdam Connection : Level 4 (Cambridge ...         Sue Leather   
6                         Les Particules Elementaires  Michel Houellebecq   
7                                     A Painted House        JOHN GRISHAM   
8                                     A Painted House        JOHN GRISHAM   
9                                           Lightning      Dean R. Koontz   
10                                          Lightning      Dean R. Koontz   
11                                Manhattan Hunt Club           JOHN SAUL   
12                                Manhattan Hunt Club           JOHN SAUL   
13                                      Dark Paradise           TAMI HOAG   
14                                         Night Sins           TAMI HOAG   
15                                         Night Sins           TAMI HOAG   
16                                        At the Edge           David Dun   
17                                      Make Them Cry       Kevin O'Brien   
18                           Little Altars Everywhere       Rebecca Wells   
19                           Little Altars Everywhere       Rebecca Wells   

   year_of_publication                   publisher  isbn_id  
0                 2002            Ballantine Books        0  
1                 2001                      Heinle        1  
2                 1996                Warner Books        2  
3                 1996                Warner Books        2  
4                 1999  Cambridge University Press        3  
5                 2001  Cambridge University Press        4  
6                 1998                  Flammarion        5  
7                 2001                   Doubleday        6  
8                 2001                   Doubleday        6  
9                 1996    Berkley Publishing Group        7  
10                1996    Berkley Publishing Group        7  
11                2002            Ballantine Books        8  
12                2002            Ballantine Books        8  
13                1994                      Bantam        9  
14                1995                      Bantam       10  
15                1995                      Bantam       10  
16                2002              Pinnacle Books       11  
17                2002              Pinnacle Books       12  
18                2003                 HarperTorch       13  
19                2003                 HarperTorch       13

In [ ]:
df.shape

(8701, 8)

In [ ]:
#Convert the user_id variable to numeric numbers in the correct order

In [ ]:
userid_list=df.user_id.unique()
print('Lenth of user id list:', len(userid_list))

Lenth of user id list: 828


In [ ]:
def get_user_id_numeric_id(user_id):
  itemindex=np.where(userid_list==user_id)
  return itemindex[0][0]

In [ ]:
df['user_id_order']=df['user_id'].apply(get_user_id_numeric_id)

In [ ]:
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  isbn_id  user_id_order  
0                2002            Ballantine Books        0              0  
1                2001                      Heinle        1              1  
2                1996                Warner Books        2              2  
3                1996                Warner Books        2              3  
4                1999  Cambridge University Press        3              4

In [ ]:
#Re-index the columns to build a matrix

In [ ]:
new_col_order=['user_id_order','isbn_id','rating','book_title','book_author','year_of_publication','publisher','isbn_id','user_id_order']
df=df.reindex(columns=new_col_order)
df.head()

user_id_order  isbn_id  rating            book_title      book_author  \
0              0        0       0  Flesh Tones: A Novel       M. J. Rose   
1              1        1       5      Rites of Passage       Judith Rae   
2              2        2       0          The Notebook  Nicholas Sparks   
3              3        2       0          The Notebook  Nicholas Sparks   
4              4        3       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  isbn_id  user_id_order  
0                2002            Ballantine Books        0              0  
1                2001                      Heinle        1              1  
2                1996                Warner Books        2              2  
3                1996                Warner Books        2              3  
4                1999  Cambridge University Press        3              4

In [ ]:
df['user_id_order'].nunique()

user_id_order    828
user_id_order    828
dtype: int64

In [ ]:
#Split your data into two sets (training and testing)

In [ ]:
from sklearn.model_selection import train_test_split
train_data,test_data=train_test_split(df,test_size=0.3)

In [ ]:
train_data.shape

(6090, 9)

In [ ]:
test_data.shape

(2611, 9)

In [ ]:
#Make predictions based on user and item variables

In [ ]:
train_data_matrix=np.zeros((n_users,n_books))
for line in train_data.itertuples():
  train_data_matrix[line[1]-1,line[2]-1]=line[3]

In [ ]:
train_data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
test_data_matrix=np.zeros((n_users,n_books))
for line in test_data.itertuples():
  test_data_matrix[line[1]-1,line[2]-1]=line[3]

In [ ]:
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(train_data_matrix,metric='cosine')
item_similarity=pairwise_distances(train_data_matrix.T,metric='cosine')

In [ ]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [ ]:
item_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [ ]:

def predict(ratings,similarity,type='user'):
  if type == 'user':
    mean_user_rating=ratings.mean(axis=1)
    ratings_diff=(ratings - mean_user_rating[:,np.newaxis])
    pred=mean_user_rating[:,np.newaxis]/similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
  elif type== 'item':
     pred =ratings.dot(similarity)/ np.array([np.abs(similarity).sum(axis=1)])
  return pred  

In [ ]:
item_prediction = predict(train_data_matrix, item_similarity, type='item')
user_prediction = predict(train_data_matrix, user_similarity, type='user')

In [ ]:
item_prediction

array([[0.        , 0.00062112, 0.0006212 , ..., 0.00062159, 0.00062112,
        0.00062112],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05540373, 0.05540373, 0.05541061, ..., 0.05544589, 0.05540373,
        0.05540373],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
user_prediction

array([[-5.06318500e-07, -5.06318500e-07,  4.95082641e-07, ...,
         9.99033216e-08, -5.06318500e-07, -5.06318500e-07],
       [ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00, -0.00000000e+00, -0.00000000e+00],
       [ 1.87562233e-05, -4.69106487e-05,  4.26211427e-05, ...,
         8.84784711e-06, -4.69106487e-05, -4.69106487e-05],
       ...,
       [ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00, -0.00000000e+00, -0.00000000e+00],
       [ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00, -0.00000000e+00, -0.00000000e+00],
       [ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00, -0.00000000e+00, -0.00000000e+00]])

In [ ]:
#Use RMSE to evaluate the predictions

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(prediction,ground_truth):
  prediction=prediction[ground_truth.nonzero()].flatten()
  ground_truth=ground_truth[ground_truth.nonzero()].flatten()
  return sqrt(mean_squared_error(prediction,ground_truth))

In [ ]:
print('user-based CF RMSE: ' + str(rmse(user_prediction, test_data_matrix)))
print('item-based CF RMSE: ' + str(rmse(item_prediction, test_data_matrix)))

user-based CF RMSE: 7.675784357217782
item-based CF RMSE: 7.657953681235128
