In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('iphone_purchase_records.csv')

In [3]:
df.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [4]:
df.dtypes

Gender             object
Age                 int64
Salary              int64
Purchase Iphone     int64
dtype: object

In [5]:
df.isnull().sum()

Gender             0
Age                0
Salary             0
Purchase Iphone    0
dtype: int64

In [6]:
df['Purchase Iphone'].value_counts()

0    257
1    143
Name: Purchase Iphone, dtype: int64

In [7]:
# Independent variable

In [8]:
X=df.iloc[:,:-1].values
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [9]:
# Dep Variable
y=df.iloc[:,3].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [10]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [11]:
X[:,0]=le.fit_transform(X[:,0])

In [12]:
X

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

In [13]:
from pandas.core.common import random_state
# train set and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [14]:
X_train.shape


(300, 3)

In [15]:
X_test.shape

(100, 3)

In [16]:
#Apply scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)

StandardScaler()

In [17]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [18]:
X_train

array([[-0.98019606,  0.58164944, -0.88670699],
       [ 1.02020406, -0.60673761,  1.46173768],
       [-0.98019606, -0.01254409, -0.5677824 ],
       [-0.98019606, -0.60673761,  1.89663484],
       [-0.98019606,  1.37390747, -1.40858358],
       [-0.98019606,  1.47293972,  0.99784738],
       [ 1.02020406,  0.08648817, -0.79972756],
       [ 1.02020406, -0.01254409, -0.24885782],
       [-0.98019606, -0.21060859, -0.5677824 ],
       [-0.98019606, -0.21060859, -0.19087153],
       [-0.98019606, -0.30964085, -1.29261101],
       [ 1.02020406, -0.30964085, -0.5677824 ],
       [ 1.02020406,  0.38358493,  0.09905991],
       [-0.98019606,  0.8787462 , -0.59677555],
       [-0.98019606,  2.06713324, -1.17663843],
       [ 1.02020406,  1.07681071, -0.13288524],
       [-0.98019606,  0.68068169,  1.78066227],
       [-0.98019606, -0.70576986,  0.56295021],
       [-0.98019606,  0.77971394,  0.35999821],
       [-0.98019606,  0.8787462 , -0.53878926],
       [ 1.02020406, -1.20093113, -1.582

In [19]:
X_test

array([[ 1.02020406, -0.80480212,  0.50496393],
       [-0.98019606, -0.01254409, -0.5677824 ],
       [ 1.02020406, -0.30964085,  0.1570462 ],
       [-0.98019606, -0.80480212,  0.27301877],
       [-0.98019606, -0.30964085, -0.5677824 ],
       [ 1.02020406, -1.10189888, -1.43757673],
       [-0.98019606, -0.70576986, -1.58254245],
       [ 1.02020406, -0.21060859,  2.15757314],
       [-0.98019606, -1.99318916, -0.04590581],
       [ 1.02020406,  0.8787462 , -0.77073441],
       [ 1.02020406, -0.80480212, -0.59677555],
       [-0.98019606, -1.00286662, -0.42281668],
       [ 1.02020406, -0.11157634, -0.42281668],
       [ 1.02020406,  0.08648817,  0.21503249],
       [ 1.02020406, -1.79512465,  0.47597078],
       [-0.98019606, -0.60673761,  1.37475825],
       [ 1.02020406, -0.11157634,  0.21503249],
       [ 1.02020406, -1.89415691,  0.44697764],
       [-0.98019606,  1.67100423,  1.75166912],
       [ 1.02020406, -0.30964085, -1.37959044],
       [-0.98019606, -0.30964085, -0.654

In [20]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [21]:
y_pred=classifier.predict(X_test)

In [22]:
classifier.score(X_test,y_test)


0.91

In [23]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[66  2]
 [ 7 25]]


In [24]:

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.91


In [25]:
from sklearn.metrics import precision_score
print(precision_score(y_test,y_pred))

0.9259259259259259


In [26]:
from sklearn.metrics import recall_score
print(recall_score(y_test,y_pred))

0.78125


In [29]:
classifier.predict([[1,23,30000]])

array([1])